                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- autoinsurance topic -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-6446750074859678"
                     data-ad-slot="1603643141"
                     data-ad-format="auto"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
